
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmyabuyzdvjlwqpqxcnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdteWFidXl6ZHZqbHdxcHF4Y25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODY5MjksImV4cCI6MjA1NzI2MjkyOX0.lSFb-x_UGiaD0yYrGz9rA_cWHRAh94v-V55TnPQluD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
